//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.1.1
//     from Assets/Scripts/Input/GopherInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @GopherInputActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @GopherInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""GopherInputActions"",
    ""maps"": [
        {
            ""name"": ""Gopher"",
            ""id"": ""8799d70f-0288-4313-a7a5-a8b2f432b3ae"",
            ""actions"": [
                {
                    ""name"": ""Move 3D"",
                    ""type"": ""Value"",
                    ""id"": ""049c3fd5-305a-45bb-b9bc-ebff21aa51f1"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Rotate 3D"",
                    ""type"": ""Value"",
                    ""id"": ""44aa8fed-bdf0-451d-9d37-b9a294cdb265"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Gripper"",
                    ""type"": ""Value"",
                    ""id"": ""fc4aa252-ff65-4911-92e2-720740b801ea"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Select Base"",
                    ""type"": ""Button"",
                    ""id"": ""91fac2fa-f22b-4c66-8633-329e4bf9acc7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select Right Arm"",
                    ""type"": ""Button"",
                    ""id"": ""7d945ee5-1686-47ed-a3ee-3ee1907bded8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select Left Arm"",
                    ""type"": ""Button"",
                    ""id"": ""d1b9293d-47ca-4f45-b3cf-dcdaad32c799"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select Both"",
                    ""type"": ""Button"",
                    ""id"": ""52330af8-e101-4e56-ad1b-727a7b5c86a6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Camera Head"",
                    ""type"": ""Button"",
                    ""id"": ""73f97052-74fe-465a-b2cc-f502cb2d3b65"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Camera Left"",
                    ""type"": ""Button"",
                    ""id"": ""63f326a2-34af-4c08-b238-9faad720709f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Camera Right"",
                    ""type"": ""Button"",
                    ""id"": ""bd3c4b65-a773-44d1-825b-cf785ee4d7b9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""3D Vector"",
                    ""id"": ""98dad55f-4541-4076-8b5a-a0963be5a37a"",
                    ""path"": ""3DVector(mode=1)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move 3D"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""d185a467-6035-481d-962d-2ada49aaa50b"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move 3D"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""d1807881-d3ff-40ff-a31b-c4ca74ae421f"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move 3D"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""b33cfe26-1fa9-4179-bd5a-66e4e7f478a8"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move 3D"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""0f09a7bf-edab-4a02-8bba-03a4fc0488ba"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move 3D"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""forward"",
                    ""id"": ""ccaf17af-24d3-48e3-8e5e-47cedcd2cbb4"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move 3D"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""backward"",
                    ""id"": ""f5417da3-45c8-42bd-93ff-6f442c8f3258"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move 3D"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""3D Vector"",
                    ""id"": ""b237a296-1664-4197-8945-46a5c684e4b1"",
                    ""path"": ""3DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate 3D"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""66a5b66d-c456-44f1-a3b7-1582162d3889"",
                    ""path"": ""<Keyboard>/numpad8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate 3D"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""566d8b86-5515-48c1-921e-35edd88335fe"",
                    ""path"": ""<Keyboard>/numpad5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate 3D"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""f110c058-3b12-45c3-be45-881e9e9f0614"",
                    ""path"": ""<Keyboard>/numpad4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate 3D"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""ff5d223f-3c20-40be-b7f0-dc41d7db1b28"",
                    ""path"": ""<Keyboard>/numpad6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate 3D"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""forward"",
                    ""id"": ""a518a0fe-fc9d-4842-87f1-f47f0e86cc33"",
                    ""path"": ""<Keyboard>/numpad7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate 3D"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""backward"",
                    ""id"": ""bc0135aa-d461-4903-9ab8-7b5a3a7fe02c"",
                    ""path"": ""<Keyboard>/numpad9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate 3D"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""5b558122-29f6-42e8-ab7f-d07acc7e5ad5"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Gripper"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""638787b9-184e-4309-866e-8f933804c832"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Gripper"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""0f37794c-7625-46f6-944c-3eb8a9435c38"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Gripper"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""21b1b3eb-60e2-489a-9de5-dfee7d57ed3b"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select Right Arm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0b4a60cb-fcad-41fb-8a42-0758730d0f9b"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select Left Arm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""76365a48-93b0-44c8-a31d-910bef33c888"",
                    ""path"": ""<Keyboard>/numpad1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Camera Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8a364391-ae68-4d23-92d5-d390a6322bda"",
                    ""path"": ""<Keyboard>/numpad3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Camera Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""807791e6-cdca-4ab4-b41c-b3a0e92c3d96"",
                    ""path"": ""<Keyboard>/numpad2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Camera Head"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fd2ac358-ea9c-4dab-99fa-840ddd8c75db"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select Both"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""17069748-8023-44b2-b5b4-2b28e8a48b61"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select Base"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard + Mouse"",
            ""bindingGroup"": ""Keyboard + Mouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Gopher
        m_Gopher = asset.FindActionMap("Gopher", throwIfNotFound: true);
        m_Gopher_Move3D = m_Gopher.FindAction("Move 3D", throwIfNotFound: true);
        m_Gopher_Rotate3D = m_Gopher.FindAction("Rotate 3D", throwIfNotFound: true);
        m_Gopher_Gripper = m_Gopher.FindAction("Gripper", throwIfNotFound: true);
        m_Gopher_SelectBase = m_Gopher.FindAction("Select Base", throwIfNotFound: true);
        m_Gopher_SelectRightArm = m_Gopher.FindAction("Select Right Arm", throwIfNotFound: true);
        m_Gopher_SelectLeftArm = m_Gopher.FindAction("Select Left Arm", throwIfNotFound: true);
        m_Gopher_SelectBoth = m_Gopher.FindAction("Select Both", throwIfNotFound: true);
        m_Gopher_CameraHead = m_Gopher.FindAction("Camera Head", throwIfNotFound: true);
        m_Gopher_CameraLeft = m_Gopher.FindAction("Camera Left", throwIfNotFound: true);
        m_Gopher_CameraRight = m_Gopher.FindAction("Camera Right", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Gopher
    private readonly InputActionMap m_Gopher;
    private IGopherActions m_GopherActionsCallbackInterface;
    private readonly InputAction m_Gopher_Move3D;
    private readonly InputAction m_Gopher_Rotate3D;
    private readonly InputAction m_Gopher_Gripper;
    private readonly InputAction m_Gopher_SelectBase;
    private readonly InputAction m_Gopher_SelectRightArm;
    private readonly InputAction m_Gopher_SelectLeftArm;
    private readonly InputAction m_Gopher_SelectBoth;
    private readonly InputAction m_Gopher_CameraHead;
    private readonly InputAction m_Gopher_CameraLeft;
    private readonly InputAction m_Gopher_CameraRight;
    public struct GopherActions
    {
        private @GopherInputActions m_Wrapper;
        public GopherActions(@GopherInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move3D => m_Wrapper.m_Gopher_Move3D;
        public InputAction @Rotate3D => m_Wrapper.m_Gopher_Rotate3D;
        public InputAction @Gripper => m_Wrapper.m_Gopher_Gripper;
        public InputAction @SelectBase => m_Wrapper.m_Gopher_SelectBase;
        public InputAction @SelectRightArm => m_Wrapper.m_Gopher_SelectRightArm;
        public InputAction @SelectLeftArm => m_Wrapper.m_Gopher_SelectLeftArm;
        public InputAction @SelectBoth => m_Wrapper.m_Gopher_SelectBoth;
        public InputAction @CameraHead => m_Wrapper.m_Gopher_CameraHead;
        public InputAction @CameraLeft => m_Wrapper.m_Gopher_CameraLeft;
        public InputAction @CameraRight => m_Wrapper.m_Gopher_CameraRight;
        public InputActionMap Get() { return m_Wrapper.m_Gopher; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GopherActions set) { return set.Get(); }
        public void SetCallbacks(IGopherActions instance)
        {
            if (m_Wrapper.m_GopherActionsCallbackInterface != null)
            {
                @Move3D.started -= m_Wrapper.m_GopherActionsCallbackInterface.OnMove3D;
                @Move3D.performed -= m_Wrapper.m_GopherActionsCallbackInterface.OnMove3D;
                @Move3D.canceled -= m_Wrapper.m_GopherActionsCallbackInterface.OnMove3D;
                @Rotate3D.started -= m_Wrapper.m_GopherActionsCallbackInterface.OnRotate3D;
                @Rotate3D.performed -= m_Wrapper.m_GopherActionsCallbackInterface.OnRotate3D;
                @Rotate3D.canceled -= m_Wrapper.m_GopherActionsCallbackInterface.OnRotate3D;
                @Gripper.started -= m_Wrapper.m_GopherActionsCallbackInterface.OnGripper;
                @Gripper.performed -= m_Wrapper.m_GopherActionsCallbackInterface.OnGripper;
                @Gripper.canceled -= m_Wrapper.m_GopherActionsCallbackInterface.OnGripper;
                @SelectBase.started -= m_Wrapper.m_GopherActionsCallbackInterface.OnSelectBase;
                @SelectBase.performed -= m_Wrapper.m_GopherActionsCallbackInterface.OnSelectBase;
                @SelectBase.canceled -= m_Wrapper.m_GopherActionsCallbackInterface.OnSelectBase;
                @SelectRightArm.started -= m_Wrapper.m_GopherActionsCallbackInterface.OnSelectRightArm;
                @SelectRightArm.performed -= m_Wrapper.m_GopherActionsCallbackInterface.OnSelectRightArm;
                @SelectRightArm.canceled -= m_Wrapper.m_GopherActionsCallbackInterface.OnSelectRightArm;
                @SelectLeftArm.started -= m_Wrapper.m_GopherActionsCallbackInterface.OnSelectLeftArm;
                @SelectLeftArm.performed -= m_Wrapper.m_GopherActionsCallbackInterface.OnSelectLeftArm;
                @SelectLeftArm.canceled -= m_Wrapper.m_GopherActionsCallbackInterface.OnSelectLeftArm;
                @SelectBoth.started -= m_Wrapper.m_GopherActionsCallbackInterface.OnSelectBoth;
                @SelectBoth.performed -= m_Wrapper.m_GopherActionsCallbackInterface.OnSelectBoth;
                @SelectBoth.canceled -= m_Wrapper.m_GopherActionsCallbackInterface.OnSelectBoth;
                @CameraHead.started -= m_Wrapper.m_GopherActionsCallbackInterface.OnCameraHead;
                @CameraHead.performed -= m_Wrapper.m_GopherActionsCallbackInterface.OnCameraHead;
                @CameraHead.canceled -= m_Wrapper.m_GopherActionsCallbackInterface.OnCameraHead;
                @CameraLeft.started -= m_Wrapper.m_GopherActionsCallbackInterface.OnCameraLeft;
                @CameraLeft.performed -= m_Wrapper.m_GopherActionsCallbackInterface.OnCameraLeft;
                @CameraLeft.canceled -= m_Wrapper.m_GopherActionsCallbackInterface.OnCameraLeft;
                @CameraRight.started -= m_Wrapper.m_GopherActionsCallbackInterface.OnCameraRight;
                @CameraRight.performed -= m_Wrapper.m_GopherActionsCallbackInterface.OnCameraRight;
                @CameraRight.canceled -= m_Wrapper.m_GopherActionsCallbackInterface.OnCameraRight;
            }
            m_Wrapper.m_GopherActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move3D.started += instance.OnMove3D;
                @Move3D.performed += instance.OnMove3D;
                @Move3D.canceled += instance.OnMove3D;
                @Rotate3D.started += instance.OnRotate3D;
                @Rotate3D.performed += instance.OnRotate3D;
                @Rotate3D.canceled += instance.OnRotate3D;
                @Gripper.started += instance.OnGripper;
                @Gripper.performed += instance.OnGripper;
                @Gripper.canceled += instance.OnGripper;
                @SelectBase.started += instance.OnSelectBase;
                @SelectBase.performed += instance.OnSelectBase;
                @SelectBase.canceled += instance.OnSelectBase;
                @SelectRightArm.started += instance.OnSelectRightArm;
                @SelectRightArm.performed += instance.OnSelectRightArm;
                @SelectRightArm.canceled += instance.OnSelectRightArm;
                @SelectLeftArm.started += instance.OnSelectLeftArm;
                @SelectLeftArm.performed += instance.OnSelectLeftArm;
                @SelectLeftArm.canceled += instance.OnSelectLeftArm;
                @SelectBoth.started += instance.OnSelectBoth;
                @SelectBoth.performed += instance.OnSelectBoth;
                @SelectBoth.canceled += instance.OnSelectBoth;
                @CameraHead.started += instance.OnCameraHead;
                @CameraHead.performed += instance.OnCameraHead;
                @CameraHead.canceled += instance.OnCameraHead;
                @CameraLeft.started += instance.OnCameraLeft;
                @CameraLeft.performed += instance.OnCameraLeft;
                @CameraLeft.canceled += instance.OnCameraLeft;
                @CameraRight.started += instance.OnCameraRight;
                @CameraRight.performed += instance.OnCameraRight;
                @CameraRight.canceled += instance.OnCameraRight;
            }
        }
    }
    public GopherActions @Gopher => new GopherActions(this);
    private int m_KeyboardMouseSchemeIndex = -1;
    public InputControlScheme KeyboardMouseScheme
    {
        get
        {
            if (m_KeyboardMouseSchemeIndex == -1) m_KeyboardMouseSchemeIndex = asset.FindControlSchemeIndex("Keyboard + Mouse");
            return asset.controlSchemes[m_KeyboardMouseSchemeIndex];
        }
    }
    public interface IGopherActions
    {
        void OnMove3D(InputAction.CallbackContext context);
        void OnRotate3D(InputAction.CallbackContext context);
        void OnGripper(InputAction.CallbackContext context);
        void OnSelectBase(InputAction.CallbackContext context);
        void OnSelectRightArm(InputAction.CallbackContext context);
        void OnSelectLeftArm(InputAction.CallbackContext context);
        void OnSelectBoth(InputAction.CallbackContext context);
        void OnCameraHead(InputAction.CallbackContext context);
        void OnCameraLeft(InputAction.CallbackContext context);
        void OnCameraRight(InputAction.CallbackContext context);
    }
}
