//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.1.1
//     from Assets/Scripts/Input/GopherInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @GopherInputActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @GopherInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""GopherInputActions"",
    ""maps"": [
        {
            ""name"": ""Gopher"",
            ""id"": ""8799d70f-0288-4313-a7a5-a8b2f432b3ae"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""8b1626fa-4adc-483c-b45a-6a790957ea66"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Right Arm Move"",
                    ""type"": ""Value"",
                    ""id"": ""049c3fd5-305a-45bb-b9bc-ebff21aa51f1"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Right Arm Rot"",
                    ""type"": ""Value"",
                    ""id"": ""44aa8fed-bdf0-451d-9d37-b9a294cdb265"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Camera Head"",
                    ""type"": ""Button"",
                    ""id"": ""73f97052-74fe-465a-b2cc-f502cb2d3b65"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""0072e7e6-5756-4914-8d01-dd46ef9c4f30"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""6ec6fe55-84d4-4773-bf53-f56cfac84bbf"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""7c2744c3-7ba0-46e1-8998-0a515c820406"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""cae2b499-0792-4511-8ec4-89e493d6b1df"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""1f10b357-38eb-4d8d-91fe-111a97dff809"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""3D Vector"",
                    ""id"": ""98dad55f-4541-4076-8b5a-a0963be5a37a"",
                    ""path"": ""3DVector(mode=1)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Right Arm Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""d185a467-6035-481d-962d-2ada49aaa50b"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Right Arm Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""d1807881-d3ff-40ff-a31b-c4ca74ae421f"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Right Arm Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""b33cfe26-1fa9-4179-bd5a-66e4e7f478a8"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Right Arm Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""0f09a7bf-edab-4a02-8bba-03a4fc0488ba"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Right Arm Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""forward"",
                    ""id"": ""ccaf17af-24d3-48e3-8e5e-47cedcd2cbb4"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Right Arm Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""backward"",
                    ""id"": ""f5417da3-45c8-42bd-93ff-6f442c8f3258"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Right Arm Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""3D Vector"",
                    ""id"": ""b237a296-1664-4197-8945-46a5c684e4b1"",
                    ""path"": ""3DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Right Arm Rot"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""66a5b66d-c456-44f1-a3b7-1582162d3889"",
                    ""path"": ""<Keyboard>/numpad8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Right Arm Rot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""566d8b86-5515-48c1-921e-35edd88335fe"",
                    ""path"": ""<Keyboard>/numpad2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Right Arm Rot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""f110c058-3b12-45c3-be45-881e9e9f0614"",
                    ""path"": ""<Keyboard>/numpad4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Right Arm Rot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""ff5d223f-3c20-40be-b7f0-dc41d7db1b28"",
                    ""path"": ""<Keyboard>/numpad6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Right Arm Rot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""forward"",
                    ""id"": ""a518a0fe-fc9d-4842-87f1-f47f0e86cc33"",
                    ""path"": ""<Keyboard>/numpad7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Right Arm Rot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""backward"",
                    ""id"": ""bc0135aa-d461-4903-9ab8-7b5a3a7fe02c"",
                    ""path"": ""<Keyboard>/numpad9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Right Arm Rot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""807791e6-cdca-4ab4-b41c-b3a0e92c3d96"",
                    ""path"": ""<Keyboard>/numpad5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Camera Head"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard + Mouse"",
            ""bindingGroup"": ""Keyboard + Mouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Gopher
        m_Gopher = asset.FindActionMap("Gopher", throwIfNotFound: true);
        m_Gopher_Movement = m_Gopher.FindAction("Movement", throwIfNotFound: true);
        m_Gopher_RightArmMove = m_Gopher.FindAction("Right Arm Move", throwIfNotFound: true);
        m_Gopher_RightArmRot = m_Gopher.FindAction("Right Arm Rot", throwIfNotFound: true);
        m_Gopher_CameraHead = m_Gopher.FindAction("Camera Head", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Gopher
    private readonly InputActionMap m_Gopher;
    private IGopherActions m_GopherActionsCallbackInterface;
    private readonly InputAction m_Gopher_Movement;
    private readonly InputAction m_Gopher_RightArmMove;
    private readonly InputAction m_Gopher_RightArmRot;
    private readonly InputAction m_Gopher_CameraHead;
    public struct GopherActions
    {
        private @GopherInputActions m_Wrapper;
        public GopherActions(@GopherInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_Gopher_Movement;
        public InputAction @RightArmMove => m_Wrapper.m_Gopher_RightArmMove;
        public InputAction @RightArmRot => m_Wrapper.m_Gopher_RightArmRot;
        public InputAction @CameraHead => m_Wrapper.m_Gopher_CameraHead;
        public InputActionMap Get() { return m_Wrapper.m_Gopher; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GopherActions set) { return set.Get(); }
        public void SetCallbacks(IGopherActions instance)
        {
            if (m_Wrapper.m_GopherActionsCallbackInterface != null)
            {
                @Movement.started -= m_Wrapper.m_GopherActionsCallbackInterface.OnMovement;
                @Movement.performed -= m_Wrapper.m_GopherActionsCallbackInterface.OnMovement;
                @Movement.canceled -= m_Wrapper.m_GopherActionsCallbackInterface.OnMovement;
                @RightArmMove.started -= m_Wrapper.m_GopherActionsCallbackInterface.OnRightArmMove;
                @RightArmMove.performed -= m_Wrapper.m_GopherActionsCallbackInterface.OnRightArmMove;
                @RightArmMove.canceled -= m_Wrapper.m_GopherActionsCallbackInterface.OnRightArmMove;
                @RightArmRot.started -= m_Wrapper.m_GopherActionsCallbackInterface.OnRightArmRot;
                @RightArmRot.performed -= m_Wrapper.m_GopherActionsCallbackInterface.OnRightArmRot;
                @RightArmRot.canceled -= m_Wrapper.m_GopherActionsCallbackInterface.OnRightArmRot;
                @CameraHead.started -= m_Wrapper.m_GopherActionsCallbackInterface.OnCameraHead;
                @CameraHead.performed -= m_Wrapper.m_GopherActionsCallbackInterface.OnCameraHead;
                @CameraHead.canceled -= m_Wrapper.m_GopherActionsCallbackInterface.OnCameraHead;
            }
            m_Wrapper.m_GopherActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
                @RightArmMove.started += instance.OnRightArmMove;
                @RightArmMove.performed += instance.OnRightArmMove;
                @RightArmMove.canceled += instance.OnRightArmMove;
                @RightArmRot.started += instance.OnRightArmRot;
                @RightArmRot.performed += instance.OnRightArmRot;
                @RightArmRot.canceled += instance.OnRightArmRot;
                @CameraHead.started += instance.OnCameraHead;
                @CameraHead.performed += instance.OnCameraHead;
                @CameraHead.canceled += instance.OnCameraHead;
            }
        }
    }
    public GopherActions @Gopher => new GopherActions(this);
    private int m_KeyboardMouseSchemeIndex = -1;
    public InputControlScheme KeyboardMouseScheme
    {
        get
        {
            if (m_KeyboardMouseSchemeIndex == -1) m_KeyboardMouseSchemeIndex = asset.FindControlSchemeIndex("Keyboard + Mouse");
            return asset.controlSchemes[m_KeyboardMouseSchemeIndex];
        }
    }
    public interface IGopherActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnRightArmMove(InputAction.CallbackContext context);
        void OnRightArmRot(InputAction.CallbackContext context);
        void OnCameraHead(InputAction.CallbackContext context);
    }
}
